feat: update setup script

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -6,71 +6,68 @@ help() {
   cat << 'HELP'
 Usage: dotfiles COMMAND
 
-  setup                           Run all following commands
-  install_requirements_on_ubuntu  Install essential utilities on Ubuntu
-  install_requirements_on_darwin  Install essential utilities on Darwin
-  link                            Create symlink to dotfiles
-  setup_fish                      Configure fish shell
-  setup_git                       Configure git
+  setup         Run all following commands
+  bootstrap     Install essential utilities
+  link          Create symlink to dotfiles
+  setup_fish    Configure fish shell
+  setup_git     Configure git
 HELP
 }
 
 setup() {
-  if test "$(lsb_release -is)" = "Ubuntu"; then
-    install_requirements_on_ubuntu
-  fi
-
-  if test "$(uname)" = "Darwin"; then
-    install_requirements_on_darwin
-  fi
-
+  bootstrap
   link
   setup_fish
   setup_git
 }
 
-install_requirements_on_ubuntu() {
-  local missing_packages=()
-  which fish || missing_packages+=(fish)
-  which tmux || missing_packages+=(tmux)
-  which git || missing_packages+=(git)
-  which rg || missing_packages+=(ripgrep)
-  which fzf || missing_packages+=(fzf)
-  which direnv || missing_packages+=(direnv)
-  which zoxide || missing_packages+=(zoxide)
-  which curl || missing_packages+=(curl)
-  which jq || missing_packages+=(jq)
-  which xsel || missing_packages+=(xsel)
-  which efm-langserver || missing_packages+=(efm-langserver)
-  which shellcheck || missing_packages+=(shellcheck)
+bootstrap() {
+  if test "$(lsb_release -is 2> /dev/null)" = "Ubuntu"; then
+    local missing_packages=()
+    which fish || missing_packages+=(fish)
+    which tmux || missing_packages+=(tmux)
+    which git || missing_packages+=(git)
+    which rg || missing_packages+=(ripgrep)
+    which fzf || missing_packages+=(fzf)
+    which direnv || missing_packages+=(direnv)
+    which zoxide || missing_packages+=(zoxide)
+    which curl || missing_packages+=(curl)
+    which jq || missing_packages+=(jq)
+    which xsel || missing_packages+=(xsel)
+    which efm-langserver || missing_packages+=(efm-langserver)
+    which shellcheck || missing_packages+=(shellcheck)
 
-  if test "${#missing_packages[@]}" -eq 0; then
-    echo "info: all required packages are installed. skip." >&2
+    if test "${#missing_packages[@]}" -eq 0; then
+      echo "info: all required packages are installed. skip." >&2
+    else
+      echo "info: install ${missing_packages[*]}" >&2
+      sudo apt install "${missing_packages[@]}"
+    fi
+
+  elif test "$(uname)" = "Darwin"; then
+    local missing_packages=()
+    which fish || missing_packages+=(fish)
+    which tmux || missing_packages+=(tmux)
+    which git || missing_packages+=(git)
+    which rg || missing_packages+=(ripgrep)
+    which fzf || missing_packages+=(fzf)
+    which direnv || missing_packages+=(direnv)
+    which zoxide || missing_packages+=(zoxide)
+    which curl || missing_packages+=(curl)
+    which jq || missing_packages+=(jq)
+    which nvim || missing_packages+=(neovim)
+    which efm-langserver || missing_packages+=(efm-langserver)
+    which shellcheck || missing_packages+=(shellcheck)
+
+    if test "${#missing_packages[@]}" -eq 0; then
+      echo "info: all required packages are installed. skip." >&2
+    else
+      echo "info: install ${missing_packages[*]}" >&2
+      brew install "${missing_packages[@]}"
+    fi
+
   else
-    echo "info: install ${missing_packages[*]}" >&2
-    sudo apt install "${missing_packages[@]}"
-  fi
-}
-
-install_requirements_on_darwin() {
-  local missing_packages=()
-  which fish || missing_packages+=(fish)
-  which tmux || missing_packages+=(tmux)
-  which git || missing_packages+=(git)
-  which rg || missing_packages+=(ripgrep)
-  which fzf || missing_packages+=(fzf)
-  which direnv || missing_packages+=(direnv)
-  which zoxide || missing_packages+=(zoxide)
-  which curl || missing_packages+=(curl)
-  which jq || missing_packages+=(jq)
-  which efm-langserver || missing_packages+=(efm-langserver)
-  which shellcheck || missing_packages+=(shellcheck)
-
-  if test "${#missing_packages[@]}" -eq 0; then
-    echo "info: all required packages are installed. skip." >&2
-  else
-    echo "info: install ${missing_packages[*]}" >&2
-    brew install "${missing_packages[@]}"
+    echo "error: Unsupported platform"
   fi
 }
 
@@ -121,6 +118,13 @@ EOF
       "https://raw.githubusercontent.com/junegunn/fzf/$fzf_verion/shell/key-bindings.fish" \
       | sed 's,ct fzf-file-widget,cy fzf-file-widget,g' \
       > "$fish_fzf_keybindings" 
+  fi
+
+  if finger "$USER" | grep -q "$(which fish)"; then
+    echo "info: fish is default shell. skip." >&2
+  else
+    echo "info: set fish as default shell." >&2
+    chsh -s "$(which fish)"
   fi
 }
 
