feat(agent/sandbox): update agent-sandbox

diff --git a/agent/bin/agent-sandbox b/agent/bin/agent-sandbox
--- a/agent/bin/agent-sandbox
+++ b/agent/bin/agent-sandbox
@@ -14,9 +14,9 @@ Usage: $SCRIPT_NAME [--dockerfile FILE]
            [--platform PLATFORM]
            [--env-file FILE]
            [--allow-write] [--allow-net [DESTINATIONS]]
-           [--use-volume DIRECTORIES]
+           [--volume [NAME:]CONTAINER_DIR]
            [--mount-writable HOST_DIR:CONTAINER_DIR] [--mount-readonly HOST_DIR:CONTAINER_DIR]
-           [--publish [[HOST_ADDRESS:]HOST_PORT:]CONTAINER_PORT]
+           [--publish [HOST_ADDRESS:]HOST_PORT:CONTAINER_PORT]
            [--tty]
            [--no-cache]
            [--verbose] [--dry-run]
@@ -27,19 +27,23 @@ Options:
   --dockerfile FILE         Path to the Dockerfile. If not set, a preset Dockerfile is used.
                             The container must include bash, iptables, ip, dnsmasq, and dig commands.
   --env-file FILE           Path to a .env file To load environment variables from.
-  --platform                Specify the platform for image building and container execution (e.g., linux/arm64 or linux/amd64).
+  --platform                Specify the platform for image building and container execution
+                            (e.g., linux/arm64 or linux/amd64).
   --allow-write             Allow write access to the project root inside the container.
                             By default, the project root (git root or current directory) is read-only.
-  --allow-net DESTINATIONS  Allow connections to specified domains or IP addresses. Separate multiple destinations with commas.
+  --allow-net DESTINATIONS  Allow connections to specified domains or IP addresses.
+                            Separate multiple destinations with commas.
                             If no port is given, only HTTPS (443) is allowed.
-  --use-volume DIRECTORIES  Mount specified directories as volumes inside the container. Separate multiple directories with commas.
-                            The volume is mounted at the absolute path of the directory inside the container.
+  --volume [NAME:]CONTAINER_DIR
+                            Mount a writable Docker volume to a container path.
+                            If NAME is not given, a volume name is generated.
   --mount-readonly HOST_DIR:CONTAINER_DIR
                             Mount a host file or directory to a container path as read-only.
   --mount-writable HOST_DIR:CONTAINER_DIR
                             Mount a host file or directory to a container path as writable.
-  --publish [[HOST_ADDRESS:]HOST_PORT:]CONTAINER_PORT
-                            Publish container port(s) to the host. If no host address is given, the port binds to 127.0.0.1 by default.
+  --publish [HOST_ADDRESS:]HOST_PORT:CONTAINER_PORT
+                            Publish container port(s) to the host.
+                            If no host address is given, the port binds to 127.0.0.1 by default.
   --tty                     Allocate a pseudo-TTY for the container.
   --no-cache                Don't use cache when building the image.
   --verbose                 Output verbose logs to stderr.
@@ -54,16 +58,16 @@ Examples:
     $SCRIPT_NAME --tty --verbose --dry-run zsh
 
   Run Claude Code:
-    $SCRIPT_NAME --allow-write --tty claude
+    $SCRIPT_NAME --allow-write --allow-net --tty claude
 
   Run Gemini CLI:
-    $SCRIPT_NAME --allow-write --tty gemini
+    $SCRIPT_NAME --allow-write --allow-net --tty gemini
 
   Run with Dockerfile:
     $SCRIPT_NAME --dockerfile .agent/sandbox/Dockerfile --verbose --tty bash
 
   Allow write access to project directory and network access to NPM:
-    $SCRIPT_NAME --dockerfile .agent/sandbox/Dockerfile --verbose --allow-write --allow-net registry.npmjs.org --use-volume node_modules npm install
+    $SCRIPT_NAME --dockerfile .agent/sandbox/Dockerfile --verbose --allow-write --allow-net registry.npmjs.org --volume node_modules npm install
 
   Allow access to docker host port:
     $SCRIPT_NAME --dockerfile .agent/sandbox/Dockerfile --verbose --allow-net host.docker.internal:3306 npm run test
@@ -93,27 +97,18 @@ RUN curl -fsSL https://grml.org/console/zshrc -o /etc/skel/.zshrc \
 
 # mise-en-place: https://mise.jdx.dev/
 RUN install -dm 755 /etc/apt/keyrings \
-    && curl -fsSL https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | tee /etc/apt/keyrings/mise-archive-keyring.gpg 1> /dev/null \
+    && wget -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | tee /etc/apt/keyrings/mise-archive-keyring.gpg 1> /dev/null \
     && echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=$(dpkg --print-architecture)] https://mise.jdx.dev/deb stable main" | tee /etc/apt/sources.list.d/mise.list \
     && apt update \
     && apt install -y mise \
     && echo 'eval "$(mise activate bash)"' >> /etc/skel/.bashrc \
     && echo 'eval "$(mise activate bash)"' >> /etc/skel/.zshrc
 
-# GitHub CLI: https://github.com/cli/cli
-RUN mkdir -p -m 755 /etc/apt/keyrings \
-    && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
-    && cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
-    && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
-    && mkdir -p -m 755 /etc/apt/sources.list.d \
-    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
-    && apt update \
-    && apt install gh -y
-
+# Create user
 RUN groupadd sandbox \
     && useradd -g sandbox -m sandbox \
-    && mkdir -p /sandbox/tools \
-    && chown sandbox:sandbox /sandbox/tools
+    && mkdir -p /sandbox/tools && chown sandbox:sandbox /sandbox/tools
+
 USER sandbox
 
 # Install Node.js
@@ -122,13 +117,24 @@ RUN curl -fsSL "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-l
     && env PATH=/sandbox/tools/node/bin:$PATH npm install -g npm@latest
 ENV PATH=/sandbox/tools/node/bin:$PATH
 
-# Install Coding Agents
+# Install coding agents
 RUN npm install -g @anthropic-ai/claude-code \
     && npm install -g ccusage \
     && npm install -g @google/gemini-cli \
+    && npm install -g @openai/codex \
     && rm -rf /home/sandbox/.npm
 
+RUN echo 'test -L ~/.bash_history || (touch /persistent/home/.bash_history; ln -sf /persistent/home/.bash_history ~/)' >> /home/sandbox/.bashrc \
+    && echo 'test -L ~/.zsh_history || (touch /persistent/home/.zsh_history; ln -sf /persistent/home/.zsh_history ~/)' >> /home/sandbox/.zshrc.local \
+    && echo 'test -L ~/.gitconfig || (touch /persistent/home/.gitconfig; ln -sf /persistent/home/.gitconfig ~/)' | tee -a /home/sandbox/.bashrc /home/sandbox/.zshrc.local \
+    && echo 'test -L ~/.local || (mkdir -p /persistent/home/.local/share; ln -sf /persistent/home/.local ~/)' | tee -a /home/sandbox/.bashrc /home/sandbox/.zshrc.local \
+    && echo 'test -L ~/.claude || (mkdir -p /persistent/home/.claude; ln -sf /persistent/home/.claude ~/)' | tee -a /home/sandbox/.bashrc /home/sandbox/.zshrc.local \
+    && echo 'test -L ~/.claude.json || (touch /persistent/home/.claude.json; ln -sf /persistent/home/.claude.json ~/)' | tee -a /home/sandbox/.bashrc /home/sandbox/.zshrc.local \
+    && echo 'test -L ~/.gemini || (mkdir -p /persistent/home/.gemini; ln -sf /persistent/home/.gemini ~/)' | tee -a /home/sandbox/.bashrc /home/sandbox/.zshrc.local \
+    && echo 'test -L ~/.codex || (mkdir -p /persistent/home/.codex; ln -sf /persistent/home/.codex ~/)' | tee -a /home/sandbox/.bashrc /home/sandbox/.zshrc.local
+
 ENV EDITOR="busybox vi"
+ENV MISE_DATA_DIR=/persistent/mise-data
 EOF
 }
 
@@ -162,26 +168,36 @@ main() {
       --allow-net   )
         allow_net="yes"
         if test -n "$2" && ! grep -q "^--" <<< "$2"; then
-          IFS=',' read -r -a allow_net_destinations <<< "$2"
+          local new_allow_net_destinations
+          IFS=',' read -r -a new_allow_net_destinations <<< "$2"
+          allow_net_destinations+=("${new_allow_net_destinations[@]}")
           shift 2
         else
           shift 1
         fi
         ;;
-      --use-volume  )
-        IFS=',' read -r -a volume_dirs <<< "$2"
+      --volume  )
+        local new_volume_dirs
+        IFS=',' read -r -a new_volume_dirs <<< "$2"
+        volume_dirs+=("${new_volume_dirs[@]}")
         shift 2
         ;;
       --mount-readonly)
-        IFS=',' read -r -a readonly_mounts <<< "$2"
+        local new_readonly_mounts
+        IFS=',' read -r -a new_readonly_mounts <<< "$2"
+        readonly_mounts+=("${new_readonly_mounts[@]}")
         shift 2
         ;;
       --mount-writable)
-        IFS=',' read -r -a writable_mounts <<< "$2"
+        local new_writable_mounts
+        IFS=',' read -r -a new_writable_mounts <<< "$2"
+        writable_mounts+=("${new_writable_mounts[@]}")
         shift 2
         ;;
       --publish     )
-        IFS=',' read -r -a publish_ports <<< "$2"
+        local new_publish_ports
+        IFS=',' read -r -a new_publish_ports <<< "$2"
+        publish_ports+=("${new_publish_ports[@]}")
         shift 2
         ;;
       --env-file    )
@@ -224,93 +240,6 @@ main() {
   # stdout to stderr
   exec 1>&2
 
-  if test -z "$dockerfile"; then
-    log "Dockerfile not specified, using preset."
-    "$SCRIPT_PATH" print_preset_dockerfile
-
-    # Persist project files: shell history, .local
-    local host_project_persistent_dir=".$SCRIPT_NAME/persistent"
-    log "Setting up project persistent directory: $host_project_persistent_dir"
-
-    local host_project_persistent_home_dir="$host_project_persistent_dir/home/sandbox"
-
-    run mkdir -p "$host_project_persistent_home_dir"
-    run touch "$host_project_persistent_home_dir/.bash_history"
-    run touch "$host_project_persistent_home_dir/.zsh_history"
-    run mkdir -p "$host_project_persistent_home_dir/.local"
-
-    writable_mounts+=(
-      "$host_project_persistent_home_dir/.bash_history:/home/sandbox/.bash_history"
-      "$host_project_persistent_home_dir/.zsh_history:/home/sandbox/.zsh_history"
-      "$host_project_persistent_home_dir/.local:/home/sandbox/.local"
-    )
-
-    # Persist shared files: .gitconfig, .git-credentials, mise data
-    local host_persistent_dir="$HOME/.$SCRIPT_NAME/persistent"
-    log "Setting up shared persistent directory: $host_persistent_dir"
-
-    local host_persistent_home_dir="$host_persistent_dir/home/sandbox"
-    run mkdir -p "$host_persistent_home_dir"
-    if ! test -e "$host_persistent_home_dir/.gitconfig"; then
-      if test "$DRY_RUN" = "no"; then
-      cat > "$host_persistent_home_dir/.gitconfig" << EOF
-[user]
-  name = "$(git config --get user.name || true)"
-  email = "$(git config --get user.email || true)"
-EOF
-      else
-        echo "DRY_RUN: cat > '$host_persistent_home_dir/.gitconfig' << EOF..."
-      fi
-    fi
-    run touch "$host_persistent_home_dir/.git-credentials"
-    run mkdir -p "$host_persistent_home_dir/.local/share/mise"
-
-    writable_mounts+=(
-      "$host_persistent_home_dir/.gitconfig:/home/sandbox/.gitconfig"
-      "$host_persistent_home_dir/.gitconfig:/home/sandbox/.git-credentials"
-      "$host_persistent_home_dir/.local/share/mise:/home/sandbox/.local/share/mise"
-    )
-
-    # allow access to host LLM provider configurations
-    run mkdir -p "$HOME/.claude"
-    run touch "$HOME/.claude.json"
-    run mkdir -p "$HOME/.gemini"
-
-    writable_mounts+=(
-      "$HOME/.claude:/home/sandbox/.claude"
-      "$HOME/.claude.json:/home/sandbox/.claude.json"
-      "$HOME/.gemini:/home/sandbox/.gemini"
-    )
-
-    allow_net="yes"
-    allow_net_destinations+=(
-      # mise
-      "mise-versions.jdx.dev"
-      "nodejs.org"
-      "dl.google.com"
-
-      # Claude Code
-      "api.anthropic.com"
-      "sentry.io"
-      "statsig.anthropic.com"
-      "statsig.com"
-
-      # Gemini CLI
-      "generativelanguage.googleapis.com"
-      "play.googleapis.com"
-      "oauth2.googleapis.com"
-      "cloudcode-pa.googleapis.com"
-
-      # github
-      "github.com"
-      "api.github.com"
-      "raw.githubusercontent.com"
-
-      # npm
-      "registry.npmjs.org"
-    )
-  fi  
-
   local host_user_id
   local host_group_id
   host_user_id=$(id -u)
@@ -331,6 +260,52 @@ EOF
 
   CONTAINER_NAME="${image_name}--$(env LC_CTYPE=C tr -dc '[:alnum:]' < /dev/urandom 2> /dev/null | head -c 10 || true)"
   NETWORK_NAME="${CONTAINER_NAME}"
+
+  if test -z "$dockerfile"; then
+    log "Dockerfile not specified, using preset."
+
+    local platform_with_default="default"
+    if test -n "$platform"; then
+      platform_with_default="$platform"
+    fi
+
+    volume_dirs+=(
+      # global persistent volume
+      "${SCRIPT_NAME}--global--${platform_with_default}--mise-data:/persistent/mise-data"
+      # project local persistent volume
+      "${image_name}--home:/persistent/home"
+    )
+
+    allow_net_destinations+=(
+      # mise
+      "mise-versions.jdx.dev"
+      "nodejs.org"
+      "dl.google.com"
+
+      # github
+      "github.com"
+      "api.github.com"
+      "raw.githubusercontent.com"
+
+      # npm
+      "registry.npmjs.org"
+
+      # Claude Code
+      "api.anthropic.com"
+      "sentry.io"
+      "statsig.anthropic.com"
+      "statsig.com"
+
+      # Gemini CLI
+      "generativelanguage.googleapis.com"
+      "oauth2.googleapis.com"
+      "cloudcode-pa.googleapis.com"
+      "play.googleapis.com"
+
+      # Codex CLI
+      "api.openai.com"
+    )
+  fi
 
   if test -n "$platform"; then
     docker_build_opts+=(--platform "$platform")
@@ -384,19 +359,27 @@ EOF
   fi
   
   # volume options
+  local volume_mount_paths=()
   if test "${#volume_dirs[@]}" -gt 0; then
+    local volume_name
+    local mount_path
+
     for dir in "${volume_dirs[@]}"; do
-      volume_name="${image_name}--$(echo "$dir" | sed 's,/,-,g; s,\.,-dot-,g')"
-      mount_path="$dir"
-      if ! grep -qE "^/" <<< "$mount_path"; then
-        if ! test -e "$dir"; then
-          mkdir -p "$dir"
+      if grep -qE ':' <<< "$dir"; then
+        IFS=':' read -r volume_name mount_path <<< "$dir"
+      else
+        volume_name="${image_name}--$(echo "$dir" | sed 's,/,-,g; s,\.,-dot-,g')"
+        mount_path="$dir"
+        if ! grep -qE "^/" <<< "$mount_path"; then
+          if ! test -e "$dir"; then
+            mkdir -p "$dir"
+          fi
+          mount_path=$(readlink -f "$dir")
         fi
-        mount_path="$(readlink -f "${dir}" | sed "s,^${host_project_root},${container_project_root},")"
       fi
+
       docker_run_opts+=(--mount "type=volume,source=${volume_name},target=${mount_path},consistency=delegated")
-      log "Setting up volume ownership for $dir ($host_user_id:$host_group_id)."
-      run docker run --rm -v "${volume_name}:/mnt" busybox:latest chown "$host_user_id:$host_group_id" /mnt
+      volume_mount_paths+=("$mount_path")
     done
   fi
 
@@ -406,7 +389,11 @@ EOF
       local host_path
       local container_path
       IFS=':' read -r host_path container_path <<< "$mount"
-      docker_run_opts+=(--mount "type=bind,source=$(readlink -f "$host_path"),target=${container_path},readonly,consistency=delegated")
+      local host_abs_path="$host_path"
+      if ! grep -qE '^/' <<< "$host_path"; then
+        host_abs_path=$(readlink -f "$host_path")
+      fi
+      docker_run_opts+=(--mount "type=bind,source=${host_abs_path},target=${container_path},readonly,consistency=delegated")
     done
   fi
   
@@ -415,7 +402,11 @@ EOF
       local host_path
       local container_path
       IFS=':' read -r host_path container_path <<< "$mount"
-      docker_run_opts+=(--mount "type=bind,source=$(readlink -f "$host_path"),target=${container_path},consistency=delegated")
+      local host_abs_path="$host_path"
+      if ! grep -qE '^/' <<< "$host_path"; then
+        host_abs_path=$(readlink -f "$host_path")
+      fi
+      docker_run_opts+=(--mount "type=bind,source=${host_abs_path},target=${container_path},consistency=delegated")
     done
   fi
 
@@ -431,8 +422,8 @@ EOF
         IFS=':' read -r host_port container_port <<< "$port"
         docker_run_opts+=(--publish "127.0.0.1:${host_port}:${container_port}")
       else
-        # # container_port
-        docker_run_opts+=(--publish "127.0.0.1::${port}")
+        echo "Error: Invalid port format: $port" >&2
+        return 1
       fi
     done
   fi
@@ -513,6 +504,12 @@ EOF
   run docker run "${docker_run_opts[@]}" "${image_name}:${image_tag}" \
     "$CONTAINER_SCRIPT_PATH" start_container_dnsmasq
 
+  if test "${#volume_mount_paths[@]}" -gt 0; then
+    log "Setting up volume ownership to match host user ($host_user_id:$host_group_id)."
+    run docker exec --user 0:0 "$CONTAINER_NAME" "$CONTAINER_SCRIPT_PATH" setup_container_volume_owner \
+      "$host_user_id" "$host_group_id" "${volume_mount_paths[@]}"
+  fi
+
   if test "$allow_net" = "yes"; then
     log "Setting up firewall."
     run docker exec --user 0:0 "$CONTAINER_NAME" \
@@ -545,20 +542,24 @@ EOF
   done
   echo "nameserver 127.0.0.1" > /etc/resolv.conf
 
-  log "Starting dnsmasq."
-  log "/sandbox/etc/dnsmasq.conf"
-  cat "/sandbox/etc/dnsmasq.conf"
-  log "/etc/resolv.conf"
-  cat "/etc/resolv.conf"
-
   dnsmasq -k -C /sandbox/etc/dnsmasq.conf --log-facility /dev/stdout
+}
+
+setup_container_volume_owner() {
+  local host_user_id=$1
+  local host_group_id=$2
+  shift 2
+
+  for mount_path in "$@"; do
+    chown "$host_user_id:$host_group_id" "$mount_path"
+  done
 }
 
 setup_container_firewall() {
   local destinations=("$@")
   local addresses=()
 
-  local address_pattern='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
+  local address_pattern='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(/[0-9]{1,2})?$'
   
   for destination in "${destinations[@]}"; do
     local host="$destination"
@@ -604,17 +605,18 @@ setup_container_firewall() {
     fi
   done
   
+  local docker_host_address
   docker_host_address=$(ip route | grep default | cut -d" " -f3)
   if test -z "$docker_host_address"; then
     echo "Error: Failed to determine docker host address" >&2
     return 1
   fi
-  
+
   # reset
   iptables -F
   iptables -X
-  #iptables -t nat -F
-  #iptables -t nat -X
+  # iptables -t nat -F
+  # iptables -t nat -X
   iptables -t mangle -F
   iptables -t mangle -X
   
@@ -631,9 +633,10 @@ setup_container_firewall() {
   iptables -P FORWARD DROP
   iptables -P OUTPUT DROP
   
-  # allow docker host
+  # allow access from docker host
   iptables -A INPUT -s "$docker_host_address" -j ACCEPT
-  iptables -A OUTPUT -d "$docker_host_address" -j ACCEPT
+  # Do not allow access to docker host by default
+  # iptables -A OUTPUT -d "$docker_host_address" -j ACCEPT
   
   # allow established connections
   iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
@@ -740,7 +743,7 @@ setup_container_user() {
 
 if test "$#" -gt 0; then
   case "$1" in
-    start_container_dnsmasq | setup_container_firewall | setup_container_user | print_preset_dockerfile )
+    start_container_dnsmasq | setup_container_volume_owner | setup_container_firewall | setup_container_user | print_preset_dockerfile )
       "$@"
       ;;
     * )
