feat(agent/sandbox): dry run mode

diff --git a/agent/bin/docker-sandbox b/agent/bin/docker-sandbox
--- a/agent/bin/docker-sandbox
+++ b/agent/bin/docker-sandbox
@@ -9,7 +9,8 @@ help() {
   cat << HELP
 Usage: $SCRIPT_NAME --dockerfile FILE
            [--allow-write] [--allow-net [DESTINATIONS]]
-           [--use-volume DIRECTORIES] [--tty] [--verbose]
+           [--use-volume DIRECTORIES] [--tty]
+           [--verbose] [--dry-run]
            COMMAND
 
 Execute a command within a container defined by a Dockerfile.
@@ -26,6 +27,7 @@ Execute a command within a container defined by a Dockerfile.
                             The volume will be mounted at the absolute path of DIR inside the container.
   --tty                     Allocate a pseudo-TTY for the container.
   --verbose                 Output verbose logs to stderr.
+  --dry-run                 Do not execute the command, just print the command to stdout.
 
 Examples:
   $SCRIPT_NAME --dockerfile .agent/sandbox/Dockerfile --verbose --tty bash
@@ -41,11 +43,14 @@ main() {
   local allow_net_destinations=()
   local volume_dirs=()
   local allocate_tty="no"
-  local verbose="no"
+
+  # TODO: global
+  verbose="no"
+  dry_run="no"
   
   while test "$#" -gt 0; do
     case "$1" in
-      --help        ) help; exit 0 ;;
+      --help        ) help; return 0 ;;
       --dockerfile  ) dockerfile="$2"; shift 2 ;;
       --allow-write ) allow_write="yes"; shift ;;
       --allow-net   )
@@ -67,8 +72,9 @@ main() {
       ;;
       --tty         ) allocate_tty="yes"; shift ;;
       --verbose     ) verbose="yes"; shift ;;
+      --dry-run     ) dry_run="yes"; shift ;;
       --            ) shift; continue ;;
-      --*           ) echo "Error: unknown option: $1" >&2; exit 1 ;;
+      --*           ) echo "Error: unknown option: $1" >&2; return 1 ;;
       *             ) break ;;
     esac
   done
@@ -77,13 +83,13 @@ main() {
   if test -z "$dockerfile"; then
     echo "Error: --dockerfile is required" >&2
     help >&2
-    exit 1
+    return 1
   fi
   
   if test "$#" -eq 0; then
     echo "Error: COMMAND is required" >&2
     help >&2
-    exit 1
+    return 1
   fi
   
   log() {
@@ -91,15 +97,24 @@ main() {
     now="$(date "+%Y-%m-%d %H:%M:%S")"
     echo -e "$now" "$@"
   }
-  
+
   # save stdout, stderr
   exec 3>&1
   exec 4>&2
-  
+ 
+  run() {
+    if test "$dry_run" = "yes"; then
+      echo "DRY_RUN: $*" >&3
+      return 0
+    fi
+    "$@"
+  }
+ 
   if test "$verbose" = "no"; then
     # discard stderr
     exec 2> /dev/null
   fi
+
   # stdout to stderr
   exec 1>&2
 
@@ -118,10 +133,10 @@ main() {
 
   local image_name
   local image_tag
-  local container_name
-  local network_name
   image_name="${SCRIPT_NAME}--$(basename "$(pwd)")"
   image_tag="latest"
+
+  # TODO: global
   container_name="${image_name}--$(env LC_CTYPE=C tr -dc '[:alnum:]' < /dev/urandom 2> /dev/null | head -c 10 || true)"
   network_name="${container_name}"
   
@@ -162,7 +177,8 @@ main() {
     fi
     mount_path="$(readlink -f "${dir}" | sed "s,^${host_project_root},${container_project_root},")"
     docker_run_opts+=(--volume "${volume_name}:${mount_path}")
-    docker run --rm -v "${volume_name}:/mnt" busybox:latest chown "$host_user_id:$host_group_id" /mnt
+    log "Setting up volume ownership for $dir ($host_user_id:$host_group_id)"
+    run docker run --rm -v "${volume_name}:/mnt" busybox:latest chown "$host_user_id:$host_group_id" /mnt
   done
   
   if test "$allocate_tty" = "yes"; then
@@ -178,15 +194,18 @@ main() {
     exec 1>&2
   
     log "Stopping container"
-    docker stop -t 0 "$container_name" || true
+    run docker stop -t 0 "$container_name" || true
   
     log "Removing container"
-    docker rm -f "$container_name" || true
+    run docker rm -f "$container_name" || true
   
     if docker network inspect "$network_name" &> /dev/null; then
       log "Removing network"
-      docker network rm "$network_name"
+      run docker network rm "$network_name"
     fi
+
+    exec 3>&-
+    exec 4>&-
   
     return "$exit_status"
   }
@@ -205,14 +224,14 @@ EOF
   )"
 
   log "Building docker image"
-  if ! docker build --tag "${image_name}:${image_tag}" - < "$dockerfile"; then
+  if ! run docker build --tag "${image_name}:${image_tag}" - < "$dockerfile"; then
     log "Error: failed to build image"
-    exit 1
+    return 1
   fi
 
   if test "$allow_net" = "yes"; then
     log "Creating network"
-    docker network create "$network_name" --driver bridge \
+    run docker network create "$network_name" --driver bridge \
       -o com.docker.network.bridge.enable_ip_masquerade=true
   fi
 
@@ -220,29 +239,33 @@ EOF
   local container_default_user_group
   local container_default_user_id
   local container_default_group_id
-  container_default_user_group=$(docker run --rm "${image_name}:${image_tag}" bash -c 'echo $(id -u):$(id -g)')
+  if test "$dry_run" = "no"; then
+    container_default_user_group=$(docker run --rm "${image_name}:${image_tag}" bash -c 'echo $(id -u):$(id -g)')
+  else
+    container_default_user_group="0:0"
+  fi
   container_default_user_id=$(cut -d: -f1 <<< "$container_default_user_group")
   container_default_group_id=$(cut -d: -f2 <<< "$container_default_user_group")
   echo "Container default user and group id: $container_default_user_group"
   
   log "Starting container"
-  docker run --detach "${docker_run_opts[@]}" "${image_name}:${image_tag}" tail -f /dev/null
+  run docker run --detach "${docker_run_opts[@]}" "${image_name}:${image_tag}" tail -f /dev/null
 
   if test "$allow_net" = "yes"; then
     log "Setting up firewall"
-    docker exec --user 0:0 "$container_name" "$SCRIPT_PATH" setup_container_firewall "${allow_net_destinations[@]}"
+    run docker exec --user 0:0 "$container_name" "$SCRIPT_PATH" setup_container_firewall "${allow_net_destinations[@]}"
   fi
   
   log "Setting up container user to match host user ($host_user_id:$host_group_id) for file access"
-  docker exec --user 0:0 "$container_name" "$SCRIPT_PATH" setup_container_user \
+  run docker exec --user 0:0 "$container_name" "$SCRIPT_PATH" setup_container_user \
      "$container_default_user_id" "$container_default_group_id" \
      "$host_user_id" "$host_group_id"
   
   # restore stdout, stderr
-  exec 1>&3 3>&-
-  exec 2>&4 4>&-
+  exec 1>&3
+  exec 2>&4
   
-  docker exec "${docker_exec_opts[@]}" "$container_name" "$@"
+  run docker exec "${docker_exec_opts[@]}" "$container_name" "$@"
 }
 
 setup_container_firewall() {
@@ -291,14 +314,14 @@ setup_container_firewall() {
 
     if test "$domain_address_count" = 0; then
       echo "Error: Failed to resolve any address for $host" >&2
-      exit 1
+      return 1
     fi
   done
   
   docker_host_address=$(ip route | grep default | cut -d" " -f3)
   if test -z "$docker_host_address"; then
     echo "Error: Failed to determine docker host address" >&2
-    exit 1
+    return 1
   fi
   
   # reset
